# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3aDkAzXUpBT1D_It8tjjhXvi7K4BkWI
"""
import streamlit as st
import fitz
import chromadb
from sentence_transformers import SentenceTransformer
from transformers import pipeline

#file_name = list(uploaded.keys())[0]

uploaded_file = st.file_uploader("Upload a PDF", type="pdf")

if uploaded_file is not None:
    doc = fitz.open(stream=uploaded_file.read(), filetype="pdf")

page = doc[0]
text = page.get_text()

print("\n First page text:\n")
print(text[:500])

pages = []

for i in range(len(doc)):
    page = doc[i]
    text = page.get_text()

    pages.append({
        "page": i + 1,
        "text": text
    })

print("Total pages stored:", len(pages))

# check first page
print("\n Sample page text:\n")
print(pages[0]["text"][:500])

chunks = []

chunk_size = 500   # small size (good for AI)

for page in pages:
    text = page["text"]

    for i in range(0, len(text), chunk_size):
        chunk_text = text[i:i+chunk_size]

        chunks.append({
            "page": page["page"],
            "text": chunk_text
        })

print("Total chunks created:", len(chunks))

# Check one chunk
print("\n Sample chunk:\n")
print(chunks[0]["text"])



from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedding model loaded")

# Extract only text from chunks
chunk_texts = [c["text"] for c in chunks]

# Create embeddings
chunk_embeddings = embedding_model.encode(chunk_texts)

print(" Total embeddings created:", len(chunk_embeddings))

print(" One embedding vector length:", len(chunk_embeddings[0]))



import chromadb

# Create Chroma client (in‑memory)
chroma_client = chromadb.Client()

# Create collection
collection = chroma_client.create_collection(
    name="pdf_chatbot"
)

print("ChromaDB collection created")

for i, chunk in enumerate(chunks):
    collection.add(
        ids=[str(i)],
        embeddings=[chunk_embeddings[i].tolist()],
        documents=[chunk["text"]],
        metadatas=[{"page": chunk["page"]}]
    )

print(" All chunks stored in vector database")

print(" Total records in DB:", collection.count())


from transformers import pipeline

llm = pipeline(
    task="text-generation",
    model="google/flan-t5-base",
    max_new_tokens=200
)

print(" LLM loaded correctly")

query = "What is this document about?"

query_embedding = embedding_model.encode([query])[0]

results = collection.query(
    query_embeddings=[query_embedding.tolist()],
    n_results=3
)

retrieved_texts = results["documents"][0]
retrieved_metadata = results["metadatas"][0]

context = ""

for text, meta in zip(retrieved_texts, retrieved_metadata):
    context += f"(Page {meta['page']}) {text}\n\n"

prompt = f"""
Answer the question using only the context below.
Mention page numbers.

Context:
{context}

Question:
{query}
"""

response = llm(prompt)

print(" Answer:\n")
print(response[0]["generated_text"])

print("\n Sources:\n")
for meta in retrieved_metadata:
    print(f"Page: {meta['page']}")

chat_history = []
print(" Chat history initialized")

print("\n PDF Chatbot Ready!")
print("Type 'exit' to stop.\n")

while True:
    query = input(" Ask a question: ")

    if query.lower() == "exit":
        print(" Chat ended")
        break

    # Store user question
    chat_history.append({"role": "user", "content": query})

    # ---- VECTOR SEARCH ----
    query_embedding = embedding_model.encode([query])[0]

    results = collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=3
    )

    retrieved_texts = results["documents"][0]
    retrieved_metadata = results["metadatas"][0]

    # ---- BUILD CONTEXT ----
    context = ""
    for text, meta in zip(retrieved_texts, retrieved_metadata):
        context += f"(Page {meta['page']}) {text}\n\n"

    # ---- LLM PROMPT ----
    prompt = f"""
    Answer the question using ONLY the context below.
    Mention page numbers.
    If the answer is not found, say "I don't know".

    Context:
    {context}

    Question:
    {query}
    """

    response = llm(prompt)
    answer = response[0]["generated_text"]

    # Store assistant answer
    chat_history.append({"role": "assistant", "content": answer})

    # ---- DISPLAY ANSWER ----
    print("\n Answer:\n")
    print(answer)

    # ---- DISPLAY SOURCES (DEDUPLICATED) ----
    print("\n Sources:")
    unique_pages = sorted(set(meta["page"] for meta in retrieved_metadata))
    for page in unique_pages:
        print(f"Page: {page}")

    print("\n" + "="*60 + "\n")




# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import fitz
# import chromadb
# from sentence_transformers import SentenceTransformer
# from transformers import pipeline
# 
# # ---------------- CONFIG ----------------
# st.set_page_config(page_title="PDF Chatbot", layout="wide")
# st.title(" PDF-Based AI Chatbot")
# 
# # ---------------- SESSION STATE ----------------
# if "collection" not in st.session_state:
#     st.session_state.collection = None
# 
# if "embedding_model" not in st.session_state:
#     st.session_state.embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
# 
# if "llm" not in st.session_state:
#     st.session_state.llm = pipeline(
#         "text-generation",
#         model="google/flan-t5-base",
#         max_new_tokens=200
#     )
# 
# if "chat_history" not in st.session_state:
#     st.session_state.chat_history = []
# 
# # ---------------- PDF UPLOAD ----------------
# uploaded_file = st.file_uploader("Upload a PDF", type="pdf")
# 
# if uploaded_file and st.session_state.collection is None:
#     doc = fitz.open(stream=uploaded_file.read(), filetype="pdf")
# 
#     pages = []
#     for i in range(len(doc)):
#         pages.append({"page": i + 1, "text": doc[i].get_text()})
# 
#     # Chunking
#     chunks = []
#     chunk_size = 500
#     for page in pages:
#         for i in range(0, len(page["text"]), chunk_size):
#             chunks.append({
#                 "page": page["page"],
#                 "text": page["text"][i:i+chunk_size]
#             })
# 
#     # Embeddings
#     texts = [c["text"] for c in chunks]
#     embeddings = st.session_state.embedding_model.encode(texts)
# 
#     # Vector DB
#     client = chromadb.Client()
#     collection = client.create_collection(name="pdf_chatbot")
# 
#     for i, chunk in enumerate(chunks):
#         collection.add(
#             ids=[str(i)],
#             embeddings=[embeddings[i].tolist()],
#             documents=[chunk["text"]],
#             metadatas=[{"page": chunk["page"]}]
#         )
# 
#     st.session_state.collection = collection
#     st.success(" PDF processed successfully!")
# 
# # ---------------- CHAT UI ----------------
# if st.session_state.collection:
#     query = st.text_input("Ask a question about the PDF")
# 
#     if query:
#         # Retrieval
#         query_embedding = st.session_state.embedding_model.encode([query])[0]
#         results = st.session_state.collection.query(
#             query_embeddings=[query_embedding.tolist()],
#             n_results=3
#         )
# 
#         retrieved_texts = results["documents"][0]
#         retrieved_metadata = results["metadatas"][0]
# 
#         # Context
#         context = ""
#         for text, meta in zip(retrieved_texts, retrieved_metadata):
#             context += f"(Page {meta['page']}) {text}\n\n"
# 
#         # Prompt
#         prompt = f"""
#         Answer the question using ONLY the context below.
#         Mention page numbers.
# 
#         Context:
#         {context}
# 
#         Question:
#         {query}
#         """
# 
#         response = st.session_state.llm(prompt)[0]["generated_text"]
# 
#         # Save history
#         st.session_state.chat_history.append((query, response))
# 
#         # Display
#         st.subheader("Answer")
#         st.write(response)
# 
#         st.subheader(" Sources")
#         pages = sorted(set(meta["page"] for meta in retrieved_metadata))
#         for p in pages:
#             st.write(f"Page {p}")
# 
# # ---------------- CHAT HISTORY ----------------
# if st.session_state.chat_history:
#     st.subheader(" Chat History")
#     for q, a in st.session_state.chat_history:
#         st.markdown(f"**Q:** {q}")
#

#!streamlit run app.py &>/content/logs.txt &

#!npm install -g localtunnel

#!lt --port 8501

